vulnerability-disclosure-policy.md

This is TTS' vulnerability disclosure policy, with a first pass at systems in scope and the right reporting endpoints (email address, and a Google Form).
It's rendered in Markdown, and will also be rendered at 18f.gsa.gov/vulnerability-disclosure-policy, similar to how our [open source policy](https://18f.gsa.gov/open-source-policy/) appears.
I included the systems I knew to safely be in scope from previous discussions. We can easily add more. For now, changes made to this document should then be manually replicated to 18f.gsa.gov.

Initial policy, scope, and reporting endpoints

---

vulnerability-disclosure-policy.md

Changes `US Government` to `U.S. government` (per 18F style), corrects several quotation marks, and removes one inconsistent period in a list.

Minor capitalization and punctuation fixes

---

vulnerability-disclosure-policy.md

Now using `tts-vulnerability-disclosure@gsa.gov`. (This was always the intent.)

Update reporting email

---

vulnerability-disclosure-policy.md

Will need the actual URL inserted I assume - helps to address; https://github.com/18F/vulnerability-disclosure-policy/issues/4

Update for Non-GPG and TLS Alternative

---

vulnerability-disclosure-policy.md

We've gotten a couple of inquiries about our use of Google Forms since releasing this policy. It's not obvious to people that this is a GSA system (with GSA and the USG's guarantees on privacy/security/records, etc.).
This mentions explicitly that GSA uses Google Apps and that both email and this form flow into the same system.

Elaborate on our use of Google Forms

---

vulnerability-disclosure-policy.md

The acronym GSA was used throughout the document, but never previously defined, so I wrote out the entire name at the first mention. Also, since this is a TTS-only policy and not a GSA-wide policy, I thought it prudent to take GSA out of the link to TTS's page.

GSA was never defined and removed from TTS link

---

vulnerability-disclosure-policy.md

This PR notes it's not just literally `cloud.gov`, but also its subdomains, since I assume we aren't limiting it to literally just the cloud.gov brochure site.
cc @kimberbat @brittag @NoahKunin

Explicitly include all subdomains of cloud.gov

---

vulnerability-disclosure-policy.md

This is important for the time being; we'll come up with a list of cloud.gov subdomains to include.

Note scope of cloud.gov policy

---

vulnerability-disclosure-policy.md

This adds a set of subdomains specified by the login.gov team, and tweaks the cloud.gov language to be consistent in phrasing.
cc @kimberbat @mzia

Add subdomains of login.gov, make surrounding language consistent

---

vulnerability-disclosure-policy.md

This is a followup to the PR at https://github.com/18F/vulnerability-disclosure-policy/pull/19 - it reverts the small change to the cloud.gov section, since it's important to be very clear that _all_ customer applications on cloud.gov are out of scope (including customer applications on custom domains as well as customer applications on *.cloud.gov domains).

Clearly exclude all cloud.gov customer apps

---

vulnerability-disclosure-policy.md

Adding "(`*.app.cloud.gov` is specifically excluded)" because it may not be clear to readers that this is a customer application domain.

More clarity for cloud.gov customer apps

---

vulnerability-disclosure-policy.md

Update to point people towards HackerOne for reporting.
Also make sure to indicate that only reports via H1 are eligible to be paid.

Add links to report via HackerOne

---

vulnerability-disclosure-policy.md

removes non-prod subdomains and clarifies primary domains in-scope.

updated policy for Login.gov

---

vulnerability-disclosure-policy.md

`idp.fr.cloud.gov` is utilized for user authentication to cloud.gov, we should explicitly add it to scope for vuln disclosure.
cc @brittag

Add idp.fr.cloud.gov to cloud.gov vdp scope

---

vulnerability-disclosure-policy.md

It's now a static site hosted on Federalist, so it doesn't feel like including it fits the goals of this policy any longer.

Remove micropurchase.18f.gov from scope

---

vulnerability-disclosure-policy.md

This removes a few domains that we aren't using anymore, and it adds new ones. This uses our ConMon Checklist (https://github.com/18F/cg-product/blob/master/ConMonChecklist.md) plus `diagrams.fr.cloud.gov` and `nessus.fr.cloud.gov`.

Update in-scope domains list for cloud.gov

---

vulnerability-disclosure-policy.md

This expands the VDP scope to all subdomains of login.gov, to match their bounty scope, and clarifies some sentences around our reporting channels.

Expand login.gov scope, clarify reporting wording

---

vulnerability-disclosure-policy.md

Add  language that clearly in-scopes credentials/PII/etc. found on the third-party services TTS uses while simultaneously out-scopes the third-party services themselves.

Add Scope For Non-Public Data

---

vulnerability-disclosure-policy.md

We're ready to have folks report potential issues with `dashboard-beta.fr.cloud.gov`.

Adding cloud.gov beta dashboard to the scope list

---

vulnerability-disclosure-policy.md

Looks like we were missing a '`' character and it was throwing the formatting off for that clump of subdomains under the _Scope_ section.

Markdown typo fix.

---

vulnerability-disclosure-policy.md

More significantly, I think we need to reconsider the 90-day clock. I've had a report that took months to fully patch because the only feasible fix was an infrastructure change that we had to get approved. I think it's fair to ask: "90 days since you last heard from us" to encourage accountability on our part, but a strict 90-day clock from report to fix is not always possible.

Fewer for countable, less for uncountable nouns
